[project]
name = "dira-checker"
version = "0.1.0"
description = "Check Dira projects for updates"
readme = "README.md"
authors = [{ name = "Or Guetta" }]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]
